### ISSUE TITLE
Output: Device does not support metal 3

### ISSUE THREAD

**Issue by 6jarjar6** [ProjectKML/metal_3_example#3]
Building and running on Apple Air M1 2020

Added to CMakeLists "set(CMAKE_OSX_ARCHITECTURES arm64)"

Build succeed, am I missing a library? Sorry I am new to building on arm64/mac/metal.

`[main] Building folder: metal_3_example 
[main] Configuring folder: metal_3_example 
[proc] Executing command: /opt/homebrew/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -S/Users/jarjar/metal_3_example -B/Users/jarjar/metal_3_example/build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is AppleClang 14.0.0.14000029
[cmake] -- The CXX compiler identification is AppleClang 14.0.0.14000029
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: /usr/bin/clang - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: /usr/bin/clang++ - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /Users/jarjar/metal_3_example/build
[build] Starting build
[proc] Executing command: /opt/homebrew/bin/cmake --build /Users/jarjar/metal_3_example/build --config Debug --target metal_3_example --
[build] [10/23   4% :: 0.328] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/allocator.cpp.o
[build] [11/23   8% :: 0.346] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/indexcodec.cpp.o
[build] [12/23  13% :: 0.360] Building C object CMakeFiles/metal_3_example.dir/include/fast_obj/fast_obj.c.o
[build] [13/23  17% :: 0.524] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/overdrawanalyzer.cpp.o
[build] [14/23  21% :: 0.548] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/indexgenerator.cpp.o
[build] [15/23  26% :: 0.553] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/clusterizer.cpp.o
[build] [16/23  30% :: 0.748] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/stripifier.cpp.o
[build] [17/23  34% :: 0.752] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/overdrawoptimizer.cpp.o
[build] [18/23  39% :: 0.758] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/spatialorder.cpp.o
[build] [19/23  43% :: 0.870] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/simplifier.cpp.o
[build] [20/23  47% :: 1.038] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/vcacheanalyzer.cpp.o
[build] [21/23  52% :: 1.041] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/vcacheoptimizer.cpp.o
[build] [22/23  56% :: 1.279] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/vfetchanalyzer.cpp.o
[build] [22/23  60% :: 1.281] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/vfetchoptimizer.cpp.o
[build] [22/23  65% :: 1.289] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/vertexcodec.cpp.o
[build] [22/23  69% :: 1.470] Building CXX object CMakeFiles/metal_3_example.dir/include/meshoptimizer/vertexfilter.cpp.o
[build] [22/23  73% :: 1.698] Building CXX object CMakeFiles/metal_3_example.dir/src/camera.cpp.o
[build] In file included from /Users/jarjar/metal_3_example/src/camera.cpp:1:
[build] In file included from /Users/jarjar/metal_3_example/src/camera.hpp:3:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/glm.hpp:132:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/packing.hpp:173:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/func_packing.inl:5:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/type_half.hpp:16:
[build] /Users/jarjar/metal_3_example/include/glm/detail/type_half.inl:9:6: warning: compound assignment to object of volatile-qualified type 'volatile float' is deprecated [-Wdeprecated-volatile]
[build]                         f *= f; // this will overflow before the for loop terminates
[build]                           ^
[build] 1 warning generated.
[build] [22/23  78% :: 1.802] Building CXX object CMakeFiles/metal_3_example.dir/src/mesh.cpp.o
[build] In file included from /Users/jarjar/metal_3_example/src/mesh.cpp:1:
[build] In file included from /Users/jarjar/metal_3_example/src/mesh.hpp:3:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/glm.hpp:132:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/packing.hpp:173:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/func_packing.inl:5:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/type_half.hpp:16:
[build] /Users/jarjar/metal_3_example/include/glm/detail/type_half.inl:9:6: warning: compound assignment to object of volatile-qualified type 'volatile float' is deprecated [-Wdeprecated-volatile]
[build]                         f *= f; // this will overflow before the for loop terminates
[build]                           ^
[build] 1 warning generated.
[build] [22/23  82% :: 1.803] Building CXX object CMakeFiles/metal_3_example.dir/src/util.cpp.o
[build] In file included from /Users/jarjar/metal_3_example/src/util.cpp:1:
[build] In file included from /Users/jarjar/metal_3_example/src/util.hpp:3:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/glm.hpp:132:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/packing.hpp:173:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/func_packing.inl:5:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/type_half.hpp:16:
[build] /Users/jarjar/metal_3_example/include/glm/detail/type_half.inl:9:6: warning: compound assignment to object of volatile-qualified type 'volatile float' is deprecated [-Wdeprecated-volatile]
[build]                         f *= f; // this will overflow before the for loop terminates
[build]                           ^
[build] 1 warning generated.
[build] [22/23  86% :: 2.177] Building CXX object CMakeFiles/metal_3_example.dir/src/metal_util.cpp.o
[build] In file included from /Users/jarjar/metal_3_example/src/metal_util.cpp:2:
[build] In file included from /Users/jarjar/metal_3_example/src/mesh.hpp:3:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/glm.hpp:132:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/packing.hpp:173:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/func_packing.inl:5:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/type_half.hpp:16:
[build] /Users/jarjar/metal_3_example/include/glm/detail/type_half.inl:9:6: warning: compound assignment to object of volatile-qualified type 'volatile float' is deprecated [-Wdeprecated-volatile]
[build]                         f *= f; // this will overflow before the for loop terminates
[build]                           ^
[build] 1 warning generated.
[build] [22/23  91% :: 2.273] Building CXX object CMakeFiles/metal_3_example.dir/src/main.cpp.o
[build] In file included from /Users/jarjar/metal_3_example/src/main.cpp:4:
[build] In file included from /Users/jarjar/metal_3_example/src/engine.hpp:3:
[build] In file included from /Users/jarjar/metal_3_example/src/camera.hpp:3:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/glm.hpp:132:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/packing.hpp:173:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/func_packing.inl:5:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/type_half.hpp:16:
[build] /Users/jarjar/metal_3_example/include/glm/detail/type_half.inl:9:6: warning: compound assignment to object of volatile-qualified type 'volatile float' is deprecated [-Wdeprecated-volatile]
[build]                         f *= f; // this will overflow before the for loop terminates
[build]                           ^
[build] 1 warning generated.
[build] [22/23  95% :: 2.393] Building CXX object CMakeFiles/metal_3_example.dir/src/engine.cpp.o
[build] In file included from /Users/jarjar/metal_3_example/src/engine.cpp:1:
[build] In file included from /Users/jarjar/metal_3_example/src/engine.hpp:3:
[build] In file included from /Users/jarjar/metal_3_example/src/camera.hpp:3:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/glm.hpp:132:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/packing.hpp:173:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/func_packing.inl:5:
[build] In file included from /Users/jarjar/metal_3_example/include/glm/detail/type_half.hpp:16:
[build] /Users/jarjar/metal_3_example/include/glm/detail/type_half.inl:9:6: warning: compound assignment to object of volatile-qualified type 'volatile float' is deprecated [-Wdeprecated-volatile]
[build]                         f *= f; // this will overflow before the for loop terminates
[build]                           ^
[build] 1 warning generated.
[build] [23/23 100% :: 2.495] Linking CXX executable /Users/jarjar/metal_3_example/bin/metal_3_example
[build] Build finished with exit code 0`

**Comment by BeastLe9enD** [comment]
@6jarjar6 What MacOS version do you have installed? The Message `Device does not support metal 3` is from the version check here
https://github.com/ProjectKML/metal_3_example/blob/7910cf09c244ad9708e06ceeb7ea5f5fe591b273/src/engine.cpp#L49
You need to have the MacOS Ventura Beta installed :)

**Comment by 6jarjar6** [comment]
> @6jarjar6 What MacOS version do you have installed? The Message `Device does not support metal 3` is from the version check here
> 
> https://github.com/ProjectKML/metal_3_example/blob/7910cf09c244ad9708e06ceeb7ea5f5fe591b273/src/engine.cpp#L49
> 
> 
> You need to have the MacOS Ventura Beta installed :)

Ah I have Monterey 12.6 I will look into upgrading. How is your reliability?

**Comment by BeastLe9enD** [comment]
I haven't had any problems with the beta version so far, except for a crash, but otherwise everything is going great.
The final version will be out in October. I still don't think it's wrong to use the beta version now :)
